---
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/products-api
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
---
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - info
        - health
        - prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
